input {
  beats {
    port => 5044
    host => "0.0.0.0"
  }
}

filter {
  # ── Traitement Cowrie ──
  if "cowrie" in [tags] {
    mutate {
      add_field => {
        "honeypot_type"    => "cowrie"
        "honeypot_host_ip" => "10.0.1.215"
        "elk_server_ip"    => "10.0.2.10"
      }
    }
    date {
      match  => ["timestamp", "ISO8601"]
      target => "@timestamp"
    }
    # Géolocalisation de l'IP source attaquante
    geoip {
      source => "src_ip"
      target => "geoip"
      fields => ["city_name","country_name","location","ip","asn"]
    }
    # Catégorisation MITRE ATT&CK
    if [eventid] == "cowrie.login.success" {
      mutate { add_field => { "attack_category" => "Initial_Access_ValidAccounts" } }
    } else if [eventid] == "cowrie.login.failed" {
      mutate { add_field => { "attack_category" => "Credential_Access_BruteForce" } }
    } else if [eventid] == "cowrie.command.input" {
      mutate { add_field => { "attack_category" => "Execution_CommandLineInterface" } }
    } else if [eventid] == "cowrie.session.file_download" {
      mutate { add_field => { "attack_category" => "C2_Ingress_Tool_Transfer" } }
    }
  }

  # ── Traitement OpenCanary ──
  if "opencanary" in [tags] {
    mutate {
      add_field => { "honeypot_type" => "opencanary" }
    }
    geoip {
      source => "src_host"
      target => "geoip"
    }
  }

  mutate {
    remove_field => ["agent", "ecs", "input", "log"]
  }
}

output {
  elasticsearch {
    hosts    => ["localhost:9200"]
    user     => "elastic"
    password => "<MOT_DE_PASSE_ELASTIC>"
    index    => "honeypot-logs-%{+YYYY.MM.dd}"
  }
  # Debug (désactiver en production)
  # stdout { codec => rubydebug }
}
